name: Model Release Workflow

on: [push]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: useblacksmith/setup-python@v6
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        pytest test_train.py
        
    - name: Execute main.py
      run: |
        python main.py
        
    - name: Upload model.keras
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: model.keras
        
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Model"
        files: |
          model.keras
